qca-ssdk: Copy Module.symvers to proper location
Currently Module.symvers is made available in temp directory
and which causes linking error in qca-nss-dp driver.

*Error snippet:
 ERROR: "fal_port_interface_eee_cfg_get" [qca-nss-dp.ko] undefined!
 ERROR: "fal_port_max_frame_size_get" [qca-nss-dp.ko] undefined!
 ERROR: "fal_mgmtctrl_ctrlpkt_profile_del" [qca-nss-dp.ko] undefined!
 make[5]: *** [__modpost] Error 1
 make[4]: *** [modules] Error 2

In order to fix this problem, we copy Module.symvers to it's
proper path.

Change-Id: I80c7177d22baf329e69c4fb8a5a56aab96d255c1
Signed-off-by: Ram Chandra Jangir <rjangir@codeaurora.org>